version: 2
updates:
  # Dependabot does not support GitHub composite actions by default (.github/actions)
  # so we need to add the folder by hand to the directories entry.
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "weekly"
    labels:
      - "type: dependency"
      - "type: github actions"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: "gradle"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type: dependency"
      - "type: gradle"
    commit-message:
      prefix: chore
      include: scope
