blank_issues_enabled: false
contact_links:
  - name: Mozilla Support Forum (SUMO)
    url: https://support.mozilla.org/en-US/products/thunderbird-android
    about: Most issues are not bugs. Ask the community for help.
