appId: net.thunderbird.android.beta
#maestro test ui-flows/shared/change_display_settings_show_contact_names.yml
---

## Open settings
- runFlow: open_display_settings.yml

### Scroll to "Show contact names"
- scrollUntilVisible:
    element:
      id: "android:id/title"
      text: "Show contact names"
    direction: DOWN
    timeout: 10000

### Check if show contact names is enabled
#to be updated

## Enable "Show contact names"
- tapOn:
    id: "android:id/title"
    text: "Show contact names"
    checked: "false"

### Close settings
- runFlow: close_display_settings.yml
