name: Pull request checks
on:
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'

env:
  CI_CHECK_RELEASE_BUILDS: 'false'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || 'no-pr' }}
  cancel-in-progress: true

jobs:
  build-k9:
    name: Build K9 application
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Prepares environment
        uses: ./.github/actions/setup

      - name: Build K9 application
        run: ./gradlew :app-k9mail:assemble

  build-thunderbird:
    name: Build Thunderbird application
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Prepares environment
        uses: ./.github/actions/setup

      - name: Build Thunderbird application
        run: ./gradlew :app-thunderbird:assemble

  build-app-ui-catalog:
    name: Build App UI-catalog application
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Prepares environment
        uses: ./.github/actions/setup

      - name: Build App UI-catalog application in Debug mode
        run: ./gradlew :app-ui-catalog:assembleDebug

  build-cli-tools:
    name: Build CLI tools if needed
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Check if CLI tools are changed
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            cli_tools_changed:
              - 'cli/**'
      - name: Build CLI tools
        # run only if CLI tools were changed
        if: steps.changes.outputs.cli_tools_changed == 'true'
        run: ./gradlew buildCliTools

  lint:
    name: Quality - Lint
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Prepares environment
        uses: ./.github/actions/setup

      - name: Running Android lint
        run: ./gradlew lint

  spotless:
    name: Quality - Spotless
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Prepares environment
        uses: ./.github/actions/setup

      - name: Running spotless check
        run: ./gradlew spotlessCheck

  detekt:
    name: Quality - Detekt
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Prepares environment
        uses: ./.github/actions/setup

      - name: Running Detekt
        run: ./gradlew detekt

      - name: Running Detekt including KMP
        # As we were not verifying detekt in KMP sources before,
        # this step is likely to fail.
        continue-on-error: true
        run: |
          ./gradlew detektMetadataCommonMain
          ./gradlew detektMetadataMain
          ./gradlew detektMetadataCommonJvmMain

  unit-test:
    name: Quality - Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Prepares environment
        uses: ./.github/actions/setup

      - name: Running unit tests
        run: ./gradlew testDebugUnitTest --parallel

  dependency-guard:
    name: Quality - Dependency Guard
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Prepares environment
        uses: ./.github/actions/setup

      - name: Running Dependency Guard
        run: ./gradlew dependencyGuard

  check-badging:
    name: Quality - Badging
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Prepares environment
        uses: ./.github/actions/setup

      - name: Running K9 Badging
        run: |
          ./gradlew :app-k9mail:checkFossReleaseBadging \
                    :app-k9mail:checkFullReleaseBadging \
                    -x assemble \
                    -x build

      - name: Running Thunderbird Badging
        run: |
          ./gradlew :app-thunderbird:checkFossBetaBadging \
                    :app-thunderbird:checkFossDailyBadging \
                    :app-thunderbird:checkFossReleaseBadging \
                    :app-thunderbird:checkFullBetaBadging \
                    :app-thunderbird:checkFullDailyBadging \
                    :app-thunderbird:checkFullReleaseBadging \
                    -x assemble \
                    -x build
