name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'

permissions:
  contents: read

concurrency:
  group: android-ci-${{ github.ref }}-${{ github.event.pull_request.number || 'no-pr' }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-common:
    name: Build common code
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1

      - name: Show disk usage
        uses: ./.github/actions/disk-usage

      - name: Cleanup disk
        uses: ./.github/actions/disk-cleanup

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle
        with:
          write-cache: ${{ github.ref == 'refs/heads/main' }}

      - name: Assemble common
        run: ./gradlew :app-common:assemble

      - name: Show disk usage
        uses: ./.github/actions/disk-usage

  build-k9:
    name: Build K9 application
    runs-on: ubuntu-latest
    timeout-minutes: 90
    needs: [build-common]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Build K9 application
        run: ./gradlew :app-k9mail:assemble

      - name: Check K9 Badging
        run: |
          ./gradlew :app-k9mail:checkFossReleaseBadging \
                    :app-k9mail:checkFullReleaseBadging \
                    -x assemble \
                    -x build

  build-thunderbird:
    name: Build Thunderbird application
    runs-on: ubuntu-latest
    timeout-minutes: 90
    needs: [build-common]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Build Thunderbird application
        run: ./gradlew :app-thunderbird:assemble

      - name: Check Thunderbird Badging
        run: |
          ./gradlew :app-thunderbird:checkFossBetaBadging \
                    :app-thunderbird:checkFossDailyBadging \
                    :app-thunderbird:checkFossReleaseBadging \
                    :app-thunderbird:checkFullBetaBadging \
                    :app-thunderbird:checkFullDailyBadging \
                    :app-thunderbird:checkFullReleaseBadging \
                    -x assemble \
                    -x build

  build-ui-catalog:
    name: Build UI-catalog application
    runs-on: ubuntu-latest
    timeout-minutes: 90
    needs: [build-common]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Build App UI-catalog application in Debug mode
        run: ./gradlew :app-ui-catalog:assembleDebug

  quality-unit-test:
    name: Quality - Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 90
    needs: [build-common]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Running unit tests
        run: ./gradlew testsOnCi --parallel

  quality-lint:
    name: Quality - Lint
    runs-on: ubuntu-latest
    timeout-minutes: 90
    needs: [build-common]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Running Android lint
        run: ./gradlew lint
