name: dependabot PR - Update dependency guard

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - '**/*.gradle'
      - 'gradle/**'
      - 'gradlew'
      - '**/libs.versions.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || 'no-pr' }}
  cancel-in-progress: true

jobs:
  update-dependency-guard:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    environment: botmobile
    timeout-minutes: 90
    steps:
      - name: App Token Generate
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        if: ${{ vars.BOT_CLIENT_ID }}
        id: app-token
        with:
          app-id: ${{ vars.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token || github.token }}

      - name: Prepares environment
        uses: ./.github/actions/setup

      - name: Update dependency guard
        run: ./gradlew :dependencyGuardBaseline

      - name: Commit and push changes if any
        env:
          APP_SLUG: ${{ steps.app-token.outputs.app-slug || 'github-actions'}}
          APP_USER_ID: ${{ vars.BOT_USER_ID || '41898282' }}
        run: |
          set -x
          
          git config --global user.name "${APP_SLUG}"
          git config --global user.email "${APP_USER_ID}+${APP_SLUG}[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git config user.name
            git config user.email
            git status
            git commit -m "chore(deps): Update dependency guard files on behalf of @dependabot"
            git log -n 2
            git push
          else
            echo "No changes to commit"
          fi

          set +x
