name: Fluidattacks - Code scanning
on:
  schedule:
    - cron: '0 10 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fluidattacks-scan:

    runs-on: ubuntu-latest

    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
        with:
          persist-credentials: false

      - name: "Run Fluidattacks scanner"
        run: |
          bash scripts/ci/run-fluidattacks-scanner.sh

      - name: "Upload scan results"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: SARIF scan results
          path: fluidscan-results.sarif
          retention-days: 5

      # Upload the results to GitHub's code scanning dashboard.
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@76621b61decf072c1cee8dd1ce2d2a82d33c17ed # v3.29.5
        with:
          sarif_file: fluidscan-results.sarif
