name: Fluidattacks - Code scanning
on:
  schedule:
    - cron: '0 10 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fluidattacks-scan:

    runs-on: ubuntu-latest

    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: "Run Fluidattacks scanners"
        run: |
          bash scripts/ci/run-fluidattacks-scanners.sh

      - name: "Upload scan results"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: SARIF scan results
          path: |
            fluidscan-sast-results.sarif
            fluidscan-sca-results.sarif
          retention-days: 5

      # Upload the results to GitHub's code scanning dashboard.
      - name: "Upload SAST results to code-scanning"
        uses: github/codeql-action/upload-sarif@9e907b5e64f6b83e7804b09294d44122997950d6 # v4.32.3
        with:
          sarif_file: fluidscan-sast-results.sarif
          category: fluidattacks-sast

      - name: "Upload SCA results to code-scanning"
        uses: github/codeql-action/upload-sarif@9e907b5e64f6b83e7804b09294d44122997950d6 # v4.32.3
        with:
          sarif_file: fluidscan-sca-results.sarif
          category: fluidattacks-sca
