
---
name: Remove answered label

on:
  issues:
    types:
      - labeled

permissions:
  issues: write

environment: botmobile

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.issue.labels.*.name, 'status: needs information') &&
      contains(github.event.issue.labels.*.name, 'status: answered')
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: App token generate
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e  # v1.11.6
        if: ${{ vars.BOT_CLIENT_ID }}
        id: app-token
        with:
          app-id: ${{ vars.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Remove answered label if both exist
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ steps.app-token.outputs.token || github.token }}
        run: |
          gh issue edit $ISSUE_NUMBER --repo "$GITHUB_REPOSITORY" --remove-label "status: answered"
