name: "NowSecure"

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build application
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./app/k9mail/build/outputs/apk/debug/k9mail-debug.apk
          retention-days: 3
  
  
  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Download application
        uses: actions/download-artifact@v2
        with:
          name: app
          
       # NOTE: ripgrep is required for line-of-code identification.
      - name: Install ripgrep
        run: sudo apt-get install -y ripgrep
        
      - name: NowSecure
        uses: nowsecure/nowsecure-action@v1
        timeout-minutes: 120
        with:
         token: ${{ secrets.NS_TOKEN }}
         app_file: k9mail-debug.apk		# REPLACE: The path to an .ipa or .apk
         group_id: "602abed9-4c66-453d-8431-da0195b682de"				# REPLACE: NowSecure Group ID

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: NowSecure.sarif

      - name: Upload SARIF to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NowSecure.sarif
          path: ./NowSecure.sarif
        
    
