name: "Validate Workflows"

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: Dry run
        default: true
      debug:
        type: boolean
        description: Debug mode
        default: false

# Declare default permissions as read only.
permissions: read-all

jobs:
  validate-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Ensure GitHub actions are SHA pinned
        env:
          DRY_RUN: ${{ !inputs.dryRun && '--no-dry-run' || '' }}
          DEBUG: ${{ inputs.debug && '--debug' || '' }}
        run: |
          bash scripts/validate-github-actions-pinned.sh $DRY_RUN $DEBUG
